modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "auctionworld"
version = "${version}"
displayName = "Auction The World"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.auctionworld]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.auctionworld]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.auctionworld]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.auctionworld]]
modId = "necronomicon"
mandatory = true
versionRange = "[1.4.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.auctionworld]]
modId = "epherolib"
mandatory = true
versionRange = "[0.1.0,)"
ordering = "AFTER"
side = "BOTH"

